### ISSUE TITLE
Wheel encoder code in Rust 

### ISSUE THREAD

**Issue by SM-dot** [UCI-HyperXite/hx9-control-system#17] opened 2024-02-06 01:01 UTC
This code basically reads the pulses from the wheel encoder and counts in clockwise and anti-clockwise direction.

**Comment by taesungh** [comment] 2024-02-06 01:06
Duplicate of #11?

**Comment by SM-dot** [comment] 2024-02-06 01:07
oops my bad

**Closed** 2024-02-06 01:12 UTC
